id: A9CA530C8
title: 'Wangdü: The Great Cloud of Blessings—The Prayer Which Magnetizes All That
  Appears and Exists'
type: translation
pechas:
- I848AC7A7
- I8A5547E9
- I666C99D9
- I440C773C
- IBE14BC1A
- IE2BEA6CB
- I44D44AEB
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - zh
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:10:27.841475
  last_modified_at: 2023-01-04 13:10:27.841482
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I848AC7A7/D5C4: 64ED
  I8A5547E9/944F: 64ED
  I666C99D9/0F99: 64ED
  I440C773C/7BB7: 64ED
  IBE14BC1A/DC84: 64ED
  IE2BEA6CB/1EB4: 64ED
  I44D44AEB/0D98: 64ED
